# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(default='nn', max_length=100),
            preserve_default=False,
        ),
    ]
