# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableviewcell',
            old_name='cell_number',
            new_name='cell_column',
        ),
        migrations.AddField(
            model_name='tableviewcell',
            name='cell_row',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
