# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20170613_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableviewcell',
            name='published_date',
        ),
    ]
